### ISSUE TITLE
Can't install jslint | Visual Studio Enterprise 2017

### ISSUE THREAD

**Issue by viniston** [benquarmby/jslintnet#35]
I'm unable to install jslint in Visual Studio Enterprise 2017 version. Please help!

**Comment by MISTech-Nelsonstud** [comment]
I was able to install it with no issues on VS2017 Enterprise 15.7.3

**Comment by FuriousLlama** [comment]
Same issue here. Looking at the log it is finding the visual studio installation.

```
Searching for applicable products...
2018-07-30 3:22:32 PM - Found installed product - Global Location
2018-07-30 3:22:32 PM - Found installed product - Visual Studio Enterprise 2017
2018-07-30 3:22:33 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by benquarmby** [comment]
I no longer use Visual Studio personally. JSLint.NET is an open source project, so folks are welcome to try their hand at adding VS 2017 integration. I should say that it wont be the trivial manifest update it was for 2015 and 2013 before it.

Alternatively, the NuGet package will continue to work across many more versions of VS.
